name: zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

concurrency:
  group: "zizmor-${{ github.ref }}"
  cancel-in-progress: false

permissions: {}

jobs:
  zizmor:
    name: Analyze
    permissions:
      contents: read
      security-events: write # required to upload SARIF results
    uses: starhaven-io/.github/.github/workflows/reusable-zizmor.yml@1d4de441c267962477971c79ddfaf555e12481d3 # v2026.07.05
